terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.0.0"
    }
  }
}

module "avm-res-azurestackhci-cluster" {
  source  = "Azure/avm-res-azurestackhci-cluster/azurerm"
  version = "2.0.2"

  {{#if adou_path}}adou_path                                       = {{hclVal adou_path}}{{/if}}
  {{#if custom_location_name}}custom_location_name                            = {{hclVal custom_location_name}}{{/if}}
  {{#if default_gateway}}default_gateway                                 = {{hclVal default_gateway}}{{/if}}
  {{#if deployment_user}}deployment_user                                 = {{hclVal deployment_user}}{{/if}}
  {{#if deployment_user_password}}deployment_user_password                        = {{hclVal deployment_user_password}}{{/if}}
  {{#if dns_servers}}dns_servers                                     = {{hclVal dns_servers}}{{/if}}
  {{#if domain_fqdn}}domain_fqdn                                     = {{hclVal domain_fqdn}}{{/if}}
  {{#if ending_address}}ending_address                                  = {{hclVal ending_address}}{{/if}}
  {{#if keyvault_name}}keyvault_name                                   = {{hclVal keyvault_name}}{{/if}}
  {{#if local_admin_password}}local_admin_password                            = {{hclVal local_admin_password}}{{/if}}
  {{#if local_admin_user}}local_admin_user                                = {{hclVal local_admin_user}}{{/if}}
  {{#if location}}location                                        = {{hclVal location}}{{/if}}
  {{#if name}}name                                            = {{hclVal name}}{{/if}}
  {{#if resource_group_id}}resource_group_id                               = {{hclVal resource_group_id}}{{/if}}
  {{#if servers}}servers                                         = {{hclVal servers}}{{/if}}
  {{#if service_principal_id}}service_principal_id                            = {{hclVal service_principal_id}}{{/if}}
  {{#if service_principal_secret}}service_principal_secret                        = {{hclVal service_principal_secret}}{{/if}}
  {{#if site_id}}site_id                                         = {{hclVal site_id}}{{/if}}
  {{#if starting_address}}starting_address                                = {{hclVal starting_address}}{{/if}}
  {{#if account_replication_type}}account_replication_type                        = {{hclVal account_replication_type}}{{/if}}
  {{#if allow_nested_items_to_be_public}}allow_nested_items_to_be_public                 = {{hclVal allow_nested_items_to_be_public}}{{/if}}
  {{#if azure_service_endpoint}}azure_service_endpoint                          = {{hclVal azure_service_endpoint}}{{/if}}
  {{#if azure_stack_lcm_user_credential_content_type}}azure_stack_lcm_user_credential_content_type    = {{hclVal azure_stack_lcm_user_credential_content_type}}{{/if}}
  {{#if azure_stack_lcm_user_credential_expiration_date}}azure_stack_lcm_user_credential_expiration_date = {{hclVal azure_stack_lcm_user_credential_expiration_date}}{{/if}}
  {{#if azure_stack_lcm_user_credential_tags}}azure_stack_lcm_user_credential_tags            = {{hclVal azure_stack_lcm_user_credential_tags}}{{/if}}
  {{#if bitlocker_boot_volume}}bitlocker_boot_volume                           = {{hclVal bitlocker_boot_volume}}{{/if}}
  {{#if bitlocker_data_volumes}}bitlocker_data_volumes                          = {{hclVal bitlocker_data_volumes}}{{/if}}
  {{#if cluster_name}}cluster_name                                    = {{hclVal cluster_name}}{{/if}}
  {{#if cluster_tags}}cluster_tags                                    = {{hclVal cluster_tags}}{{/if}}
  {{#if compute_intent_name}}compute_intent_name                             = {{hclVal compute_intent_name}}{{/if}}
  {{#if compute_override_adapter_property}}compute_override_adapter_property               = {{hclVal compute_override_adapter_property}}{{/if}}
  {{#if compute_override_qos_policy}}compute_override_qos_policy                     = {{hclVal compute_override_qos_policy}}{{/if}}
  {{#if compute_qos_policy_overrides}}compute_qos_policy_overrides                    = {{hclVal compute_qos_policy_overrides}}{{/if}}
  {{#if compute_rdma_enabled}}compute_rdma_enabled                            = {{hclVal compute_rdma_enabled}}{{/if}}
  {{#if compute_rdma_jumbo_packet}}compute_rdma_jumbo_packet                       = {{hclVal compute_rdma_jumbo_packet}}{{/if}}
  {{#if compute_rdma_protocol}}compute_rdma_protocol                           = {{hclVal compute_rdma_protocol}}{{/if}}
  {{#if compute_traffic_type}}compute_traffic_type                            = {{hclVal compute_traffic_type}}{{/if}}
  {{#if configuration_mode}}configuration_mode                              = {{hclVal configuration_mode}}{{/if}}
  {{#if create_hci_rp_role_assignments}}create_hci_rp_role_assignments                  = {{hclVal create_hci_rp_role_assignments}}{{/if}}
  {{#if create_key_vault}}create_key_vault                                = {{hclVal create_key_vault}}{{/if}}
  {{#if create_witness_storage_account}}create_witness_storage_account                  = {{hclVal create_witness_storage_account}}{{/if}}
  {{#if credential_guard_enforced}}credential_guard_enforced                       = {{hclVal credential_guard_enforced}}{{/if}}
  {{#if cross_tenant_replication_enabled}}cross_tenant_replication_enabled                = {{hclVal cross_tenant_replication_enabled}}{{/if}}
  {{#if default_arb_application_content_type}}default_arb_application_content_type            = {{hclVal default_arb_application_content_type}}{{/if}}
  {{#if default_arb_application_expiration_date}}default_arb_application_expiration_date         = {{hclVal default_arb_application_expiration_date}}{{/if}}
  {{#if default_arb_application_tags}}default_arb_application_tags                    = {{hclVal default_arb_application_tags}}{{/if}}
  {{#if deployment_configuration_version}}deployment_configuration_version                = {{hclVal deployment_configuration_version}}{{/if}}
  {{#if drift_control_enforced}}drift_control_enforced                          = {{hclVal drift_control_enforced}}{{/if}}
  {{#if drtm_protection}}drtm_protection                                 = {{hclVal drtm_protection}}{{/if}}
  {{#if enable_telemetry}}enable_telemetry                                = {{hclVal enable_telemetry}}{{/if}}
  {{#if eu_location}}eu_location                                     = {{hclVal eu_location}}{{/if}}
  {{#if hvci_protection}}hvci_protection                                 = {{hclVal hvci_protection}}{{/if}}
  {{#if intent_name}}intent_name                                     = {{hclVal intent_name}}{{/if}}
  {{#if is_exported}}is_exported                                     = {{hclVal is_exported}}{{/if}}
  {{#if key_vault_location}}key_vault_location                              = {{hclVal key_vault_location}}{{/if}}
  {{#if key_vault_resource_group}}key_vault_resource_group                        = {{hclVal key_vault_resource_group}}{{/if}}
  {{#if keyvault_purge_protection_enabled}}keyvault_purge_protection_enabled               = {{hclVal keyvault_purge_protection_enabled}}{{/if}}
  {{#if keyvault_secrets}}keyvault_secrets                                = {{hclVal keyvault_secrets}}{{/if}}
  {{#if keyvault_soft_delete_retention_days}}keyvault_soft_delete_retention_days             = {{hclVal keyvault_soft_delete_retention_days}}{{/if}}
  {{#if keyvault_tags}}keyvault_tags                                   = {{hclVal keyvault_tags}}{{/if}}
  {{#if local_admin_credential_content_type}}local_admin_credential_content_type             = {{hclVal local_admin_credential_content_type}}{{/if}}
  {{#if local_admin_credential_expiration_date}}local_admin_credential_expiration_date          = {{hclVal local_admin_credential_expiration_date}}{{/if}}
  {{#if local_admin_credential_tags}}local_admin_credential_tags                     = {{hclVal local_admin_credential_tags}}{{/if}}
  {{#if lock}}lock                                            = {{hclVal lock}}{{/if}}
  {{#if management_adapters}}management_adapters                             = {{hclVal management_adapters}}{{/if}}
  {{#if min_tls_version}}min_tls_version                                 = {{hclVal min_tls_version}}{{/if}}
  {{#if naming_prefix}}naming_prefix                                   = {{hclVal naming_prefix}}{{/if}}
  {{#if operation_type}}operation_type                                  = {{hclVal operation_type}}{{/if}}
  {{#if override_adapter_property}}override_adapter_property                       = {{hclVal override_adapter_property}}{{/if}}
  {{#if override_qos_policy}}override_qos_policy                             = {{hclVal override_qos_policy}}{{/if}}
  {{#if qos_policy_overrides}}qos_policy_overrides                            = {{hclVal qos_policy_overrides}}{{/if}}
  {{#if random_suffix}}random_suffix                                   = {{hclVal random_suffix}}{{/if}}
  {{#if rdma_enabled}}rdma_enabled                                    = {{hclVal rdma_enabled}}{{/if}}
  {{#if rdma_jumbo_packet}}rdma_jumbo_packet                               = {{hclVal rdma_jumbo_packet}}{{/if}}
  {{#if rdma_protocol}}rdma_protocol                                   = {{hclVal rdma_protocol}}{{/if}}
  {{#if resource_group_location}}resource_group_location                         = {{hclVal resource_group_location}}{{/if}}
  {{#if role_assignments}}role_assignments                                = {{hclVal role_assignments}}{{/if}}
  {{#if rp_service_principal_object_id}}rp_service_principal_object_id                  = {{hclVal rp_service_principal_object_id}}{{/if}}
  {{#if secrets_location}}secrets_location                                = {{hclVal secrets_location}}{{/if}}
  {{#if side_channel_mitigation_enforced}}side_channel_mitigation_enforced                = {{hclVal side_channel_mitigation_enforced}}{{/if}}
  {{#if smb_cluster_encryption}}smb_cluster_encryption                          = {{hclVal smb_cluster_encryption}}{{/if}}
  {{#if smb_signing_enforced}}smb_signing_enforced                            = {{hclVal smb_signing_enforced}}{{/if}}
  {{#if storage_adapter_ip_info}}storage_adapter_ip_info                         = {{hclVal storage_adapter_ip_info}}{{/if}}
  {{#if storage_connectivity_switchless}}storage_connectivity_switchless                 = {{hclVal storage_connectivity_switchless}}{{/if}}
  {{#if storage_intent_name}}storage_intent_name                             = {{hclVal storage_intent_name}}{{/if}}
  {{#if storage_networks}}storage_networks                                = {{hclVal storage_networks}}{{/if}}
  {{#if storage_override_adapter_property}}storage_override_adapter_property               = {{hclVal storage_override_adapter_property}}{{/if}}
  {{#if storage_override_qos_policy}}storage_override_qos_policy                     = {{hclVal storage_override_qos_policy}}{{/if}}
  {{#if storage_qos_policy_overrides}}storage_qos_policy_overrides                    = {{hclVal storage_qos_policy_overrides}}{{/if}}
  {{#if storage_rdma_enabled}}storage_rdma_enabled                            = {{hclVal storage_rdma_enabled}}{{/if}}
  {{#if storage_rdma_jumbo_packet}}storage_rdma_jumbo_packet                       = {{hclVal storage_rdma_jumbo_packet}}{{/if}}
  {{#if storage_rdma_protocol}}storage_rdma_protocol                           = {{hclVal storage_rdma_protocol}}{{/if}}
  {{#if storage_tags}}storage_tags                                    = {{hclVal storage_tags}}{{/if}}
  {{#if storage_traffic_type}}storage_traffic_type                            = {{hclVal storage_traffic_type}}{{/if}}
  {{#if subnet_mask}}subnet_mask                                     = {{hclVal subnet_mask}}{{/if}}
  {{#if tenant_id}}tenant_id                                       = {{hclVal tenant_id}}{{/if}}
  {{#if traffic_type}}traffic_type                                    = {{hclVal traffic_type}}{{/if}}
  {{#if use_legacy_key_vault_model}}use_legacy_key_vault_model                      = {{hclVal use_legacy_key_vault_model}}{{/if}}
  {{#if wdac_enforced}}wdac_enforced                                   = {{hclVal wdac_enforced}}{{/if}}
  {{#if witness_path}}witness_path                                    = {{hclVal witness_path}}{{/if}}
  {{#if witness_storage_account_name}}witness_storage_account_name                    = {{hclVal witness_storage_account_name}}{{/if}}
  {{#if witness_storage_account_resource_group_name}}witness_storage_account_resource_group_name     = {{hclVal witness_storage_account_resource_group_name}}{{/if}}
  {{#if witness_storage_key_content_type}}witness_storage_key_content_type                = {{hclVal witness_storage_key_content_type}}{{/if}}
  {{#if witness_storage_key_expiration_date}}witness_storage_key_expiration_date             = {{hclVal witness_storage_key_expiration_date}}{{/if}}
  {{#if witness_storage_key_tags}}witness_storage_key_tags                        = {{hclVal witness_storage_key_tags}}{{/if}}
  {{#if witness_type}}witness_type                                    = {{hclVal witness_type}}{{/if}}
}
