terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.0.0"
    }
  }
}

module "avm-res-web-site" {
  source  = "Azure/avm-res-web-site/azurerm"
  version = "0.22.0"

  {{#location}}location                                       = {{{location}}}{{/location}}
  {{#name}}name                                           = {{{name}}}{{/name}}
  {{#parent_id}}parent_id                                      = {{{parent_id}}}{{/parent_id}}
  {{#service_plan_resource_id}}service_plan_resource_id                       = {{{service_plan_resource_id}}}{{/service_plan_resource_id}}
  {{#all_child_resources_inherit_tags}}all_child_resources_inherit_tags               = {{{all_child_resources_inherit_tags}}}{{/all_child_resources_inherit_tags}}
  {{#always_ready}}always_ready                                   = {{{always_ready}}}{{/always_ready}}
  {{#app_service_active_slot}}app_service_active_slot                        = {{{app_service_active_slot}}}{{/app_service_active_slot}}
  {{#app_settings}}app_settings                                   = {{{app_settings}}}{{/app_settings}}
  {{#application_insights_connection_string}}application_insights_connection_string         = {{{application_insights_connection_string}}}{{/application_insights_connection_string}}
  {{#application_insights_key}}application_insights_key                       = {{{application_insights_key}}}{{/application_insights_key}}
  {{#auth_settings}}auth_settings                                  = {{{auth_settings}}}{{/auth_settings}}
  {{#auth_settings_v2}}auth_settings_v2                               = {{{auth_settings_v2}}}{{/auth_settings_v2}}
  {{#auto_generated_domain_name_label_scope}}auto_generated_domain_name_label_scope         = {{{auto_generated_domain_name_label_scope}}}{{/auto_generated_domain_name_label_scope}}
  {{#backup}}backup                                         = {{{backup}}}{{/backup}}
  {{#builtin_logging_enabled}}builtin_logging_enabled                        = {{{builtin_logging_enabled}}}{{/builtin_logging_enabled}}
  {{#bundle_version}}bundle_version                                 = {{{bundle_version}}}{{/bundle_version}}
  {{#certificates}}certificates                                   = {{{certificates}}}{{/certificates}}
  {{#client_affinity_enabled}}client_affinity_enabled                        = {{{client_affinity_enabled}}}{{/client_affinity_enabled}}
  {{#client_affinity_partitioning_enabled}}client_affinity_partitioning_enabled           = {{{client_affinity_partitioning_enabled}}}{{/client_affinity_partitioning_enabled}}
  {{#client_affinity_proxy_enabled}}client_affinity_proxy_enabled                  = {{{client_affinity_proxy_enabled}}}{{/client_affinity_proxy_enabled}}
  {{#client_certificate_enabled}}client_certificate_enabled                     = {{{client_certificate_enabled}}}{{/client_certificate_enabled}}
  {{#client_certificate_exclusion_paths}}client_certificate_exclusion_paths             = {{{client_certificate_exclusion_paths}}}{{/client_certificate_exclusion_paths}}
  {{#client_certificate_mode}}client_certificate_mode                        = {{{client_certificate_mode}}}{{/client_certificate_mode}}
  {{#connection_strings}}connection_strings                             = {{{connection_strings}}}{{/connection_strings}}
  {{#container_size}}container_size                                 = {{{container_size}}}{{/container_size}}
  {{#content_share_force_disabled}}content_share_force_disabled                   = {{{content_share_force_disabled}}}{{/content_share_force_disabled}}
  {{#custom_domains}}custom_domains                                 = {{{custom_domains}}}{{/custom_domains}}
  {{#daily_memory_time_quota}}daily_memory_time_quota                        = {{{daily_memory_time_quota}}}{{/daily_memory_time_quota}}
  {{#dapr_config}}dapr_config                                    = {{{dapr_config}}}{{/dapr_config}}
  {{#deployment_slots}}deployment_slots                               = {{{deployment_slots}}}{{/deployment_slots}}
  {{#deployment_slots_inherit_lock}}deployment_slots_inherit_lock                  = {{{deployment_slots_inherit_lock}}}{{/deployment_slots_inherit_lock}}
  {{#diagnostic_settings}}diagnostic_settings                            = {{{diagnostic_settings}}}{{/diagnostic_settings}}
  {{#dns_configuration}}dns_configuration                              = {{{dns_configuration}}}{{/dns_configuration}}
  {{#enable_telemetry}}enable_telemetry                               = {{{enable_telemetry}}}{{/enable_telemetry}}
  {{#enabled}}enabled                                        = {{{enabled}}}{{/enabled}}
  {{#end_to_end_encryption_enabled}}end_to_end_encryption_enabled                  = {{{end_to_end_encryption_enabled}}}{{/end_to_end_encryption_enabled}}
  {{#fc1_runtime_name}}fc1_runtime_name                               = {{{fc1_runtime_name}}}{{/fc1_runtime_name}}
  {{#fc1_runtime_version}}fc1_runtime_version                            = {{{fc1_runtime_version}}}{{/fc1_runtime_version}}
  {{#ftp_publish_basic_authentication_enabled}}ftp_publish_basic_authentication_enabled       = {{{ftp_publish_basic_authentication_enabled}}}{{/ftp_publish_basic_authentication_enabled}}
  {{#function_app_uses_fc1}}function_app_uses_fc1                          = {{{function_app_uses_fc1}}}{{/function_app_uses_fc1}}
  {{#functions_extension_version}}functions_extension_version                    = {{{functions_extension_version}}}{{/functions_extension_version}}
  {{#host_names_disabled}}host_names_disabled                            = {{{host_names_disabled}}}{{/host_names_disabled}}
  {{#hosting_environment_id}}hosting_environment_id                         = {{{hosting_environment_id}}}{{/hosting_environment_id}}
  {{#https_only}}https_only                                     = {{{https_only}}}{{/https_only}}
  {{#hyper_v}}hyper_v                                        = {{{hyper_v}}}{{/hyper_v}}
  {{#instance_memory_in_mb}}instance_memory_in_mb                          = {{{instance_memory_in_mb}}}{{/instance_memory_in_mb}}
  {{#ip_mode}}ip_mode                                        = {{{ip_mode}}}{{/ip_mode}}
  {{#key_vault_reference_identity}}key_vault_reference_identity                   = {{{key_vault_reference_identity}}}{{/key_vault_reference_identity}}
  {{#kind}}kind                                           = {{{kind}}}{{/kind}}
  {{#lock}}lock                                           = {{{lock}}}{{/lock}}
  {{#logic_app_runtime_version}}logic_app_runtime_version                      = {{{logic_app_runtime_version}}}{{/logic_app_runtime_version}}
  {{#logs}}logs                                           = {{{logs}}}{{/logs}}
  {{#managed_environment_id}}managed_environment_id                         = {{{managed_environment_id}}}{{/managed_environment_id}}
  {{#managed_identities}}managed_identities                             = {{{managed_identities}}}{{/managed_identities}}
  {{#maximum_instance_count}}maximum_instance_count                         = {{{maximum_instance_count}}}{{/maximum_instance_count}}
  {{#os_type}}os_type                                        = {{{os_type}}}{{/os_type}}
  {{#private_endpoints}}private_endpoints                              = {{{private_endpoints}}}{{/private_endpoints}}
  {{#private_endpoints_inherit_lock}}private_endpoints_inherit_lock                 = {{{private_endpoints_inherit_lock}}}{{/private_endpoints_inherit_lock}}
  {{#private_endpoints_manage_dns_zone_group}}private_endpoints_manage_dns_zone_group        = {{{private_endpoints_manage_dns_zone_group}}}{{/private_endpoints_manage_dns_zone_group}}
  {{#public_network_access_enabled}}public_network_access_enabled                  = {{{public_network_access_enabled}}}{{/public_network_access_enabled}}
  {{#redundancy_mode}}redundancy_mode                                = {{{redundancy_mode}}}{{/redundancy_mode}}
  {{#resource_config}}resource_config                                = {{{resource_config}}}{{/resource_config}}
  {{#retry}}retry                                          = {{{retry}}}{{/retry}}
  {{#role_assignments}}role_assignments                               = {{{role_assignments}}}{{/role_assignments}}
  {{#scm_publish_basic_authentication_enabled}}scm_publish_basic_authentication_enabled       = {{{scm_publish_basic_authentication_enabled}}}{{/scm_publish_basic_authentication_enabled}}
  {{#scm_site_also_stopped}}scm_site_also_stopped                          = {{{scm_site_also_stopped}}}{{/scm_site_also_stopped}}
  {{#site_config}}site_config                                    = {{{site_config}}}{{/site_config}}
  {{#slot_sensitive_app_settings}}slot_sensitive_app_settings                    = {{{slot_sensitive_app_settings}}}{{/slot_sensitive_app_settings}}
  {{#slots_storage_shares_to_mount_sensitive_values}}slots_storage_shares_to_mount_sensitive_values = {{{slots_storage_shares_to_mount_sensitive_values}}}{{/slots_storage_shares_to_mount_sensitive_values}}
  {{#ssh_enabled}}ssh_enabled                                    = {{{ssh_enabled}}}{{/ssh_enabled}}
  {{#sticky_settings}}sticky_settings                                = {{{sticky_settings}}}{{/sticky_settings}}
  {{#storage_account_access_key}}storage_account_access_key                     = {{{storage_account_access_key}}}{{/storage_account_access_key}}
  {{#storage_account_name}}storage_account_name                           = {{{storage_account_name}}}{{/storage_account_name}}
  {{#storage_account_required}}storage_account_required                       = {{{storage_account_required}}}{{/storage_account_required}}
  {{#storage_account_share_name}}storage_account_share_name                     = {{{storage_account_share_name}}}{{/storage_account_share_name}}
  {{#storage_authentication_type}}storage_authentication_type                    = {{{storage_authentication_type}}}{{/storage_authentication_type}}
  {{#storage_container_endpoint}}storage_container_endpoint                     = {{{storage_container_endpoint}}}{{/storage_container_endpoint}}
  {{#storage_container_type}}storage_container_type                         = {{{storage_container_type}}}{{/storage_container_type}}
  {{#storage_shares_to_mount}}storage_shares_to_mount                        = {{{storage_shares_to_mount}}}{{/storage_shares_to_mount}}
  {{#storage_user_assigned_identity_id}}storage_user_assigned_identity_id              = {{{storage_user_assigned_identity_id}}}{{/storage_user_assigned_identity_id}}
  {{#storage_uses_managed_identity}}storage_uses_managed_identity                  = {{{storage_uses_managed_identity}}}{{/storage_uses_managed_identity}}
  {{#tags}}tags                                           = {{{tags}}}{{/tags}}
  {{#timeouts}}timeouts                                       = {{{timeouts}}}{{/timeouts}}
  {{#use_extension_bundle}}use_extension_bundle                           = {{{use_extension_bundle}}}{{/use_extension_bundle}}
  {{#virtual_network_backup_restore_enabled}}virtual_network_backup_restore_enabled         = {{{virtual_network_backup_restore_enabled}}}{{/virtual_network_backup_restore_enabled}}
  {{#virtual_network_subnet_id}}virtual_network_subnet_id                      = {{{virtual_network_subnet_id}}}{{/virtual_network_subnet_id}}
  {{#vnet_application_traffic_enabled}}vnet_application_traffic_enabled               = {{{vnet_application_traffic_enabled}}}{{/vnet_application_traffic_enabled}}
  {{#vnet_content_share_enabled}}vnet_content_share_enabled                     = {{{vnet_content_share_enabled}}}{{/vnet_content_share_enabled}}
  {{#vnet_image_pull_enabled}}vnet_image_pull_enabled                        = {{{vnet_image_pull_enabled}}}{{/vnet_image_pull_enabled}}
  {{#vnet_route_all_traffic}}vnet_route_all_traffic                         = {{{vnet_route_all_traffic}}}{{/vnet_route_all_traffic}}
  {{#workload_profile_name}}workload_profile_name                          = {{{workload_profile_name}}}{{/workload_profile_name}}
  {{#zip_deploy_file}}zip_deploy_file                                = {{{zip_deploy_file}}}{{/zip_deploy_file}}
  {{#zip_deploy_wait_duration}}zip_deploy_wait_duration                       = {{{zip_deploy_wait_duration}}}{{/zip_deploy_wait_duration}}
}
