# --- Variable Declarations ---
variable "panorama_hostname" {
  description = "Panorama hostname or management IP"
  type        = string
}

variable "panorama_api_key" {
  description = "PAN-OS API key"
  type        = string
  sensitive   = true
}

# --- Provider Configuration ---
terraform {
  required_version = ">= 1.5.0, < 2.0.0"

  required_providers {
    panos = {
      source  = "PaloAltoNetworks/panos"
      version = "~> 2.0.12"
    }
  }
}

provider "panos" {
  hostname = var.panorama_hostname
  api_key  = var.panorama_api_key
}

# --- Security Policy Rule ---
resource "panos_security_policy_rules" "{{snakeCase rule_name}}" {
  location = {
    device_group = {
      name      = "{{device_group}}"
      rulebase  = "{{rulebase}}"
    }
  }

  position = {
    where = "{{position}}"
  }

  rules = [
    {
      name                  = "{{rule_name}}"
      description           = "Generated by IaC Generator"
      source_zones          = {{{safeArray source_zones}}}
      destination_zones     = {{{safeArray destination_zones}}}
      source_addresses      = {{{safeArray source_addresses}}}
      destination_addresses = {{{safeArray destination_addresses}}}
      applications          = {{{safeArray applications}}}
      services              = {{{safeArray services}}}
      action                = "{{action}}"
      {{#if log_end}}log_end               = {{log_end}}{{/if}}
    }
  ]
}