terraform {
  required_providers {
    panos = {
      source  = "paloaltonetworks/panos"
      version = "~> 2.0"
    }
  }
}

resource "panos_security_rule" "{{rule_name}}" {
  name                  = "{{rule_name}}"
  device_group          = "{{device_group}}"
  source_zone           = ["{{source_zone}}"]
  destination_zone      = ["{{destination_zone}}"]
  source_address        = [{{#each source_address}}"{{this}}"{{#unless @last}}, {{/unless}}{{/each}}]
  destination_address   = [{{#each destination_address}}"{{this}}"{{#unless @last}}, {{/unless}}{{/each}}]
  application           = [{{#each application}}"{{this}}"{{#unless @last}}, {{/unless}}{{/each}}]
  service               = [{{#each service}}"{{this}}"{{#unless @last}}, {{/unless}}{{/each}}]
  action                = "{{action}}"
  
  # Logging and tracking best practices
  log_setting           = "default"
  log_end               = true
  description           = "Generated by IaC Generator"
}