terraform {
  required_providers {
    panos = {
      source  = "paloaltonetworks/panos"
      version = "~> 2.0"
    }
  }
}

resource "panos_security_rule" "{{rule_name}}" {
  name                  = "{{rule_name}}"
  device_group          = "{{device_group}}"
  source_zone           = {{{safeArray source_zone}}}
  destination_zone      = {{{safeArray destination_zone}}}
  source_address        = {{{safeArray source_address}}}
  destination_address   = {{{safeArray destination_address}}}
  application           = {{{safeArray application}}}
  service               = {{{safeArray service}}}
  action                = "{{action}}"
  
  # Logging and tracking best practices
  log_setting           = "default"
  log_end               = true
  description           = "Generated by IaC Generator"
}